apiVersion: apps/v1
kind: Deployment
metadata:
    name: website-service
spec:
    replicas: 1
    revisionHistoryLimit: 1 # Keep only one old Replica Set as backup
    selector:
        matchLabels:
            app: website-service
    template:
        metadata:
            labels:
                app: website-service
        spec:
            containers:
                - name: website-service
                  image: ghcr.io/2024-sdm-group5/website-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  resources:
                      requests:
                          cpu: "100m"  # Request 100 milli-cores
                          memory: "200Mi"  # Request 200 MiB
                      limits:
                          cpu: "200m"  # Limit to 200 milli-cores
                          memory: "400Mi"  # Limit to 400 MiB
                  env:
                      - name: GOOGLE_CLIENT_ID
                        valueFrom:
                          secretKeyRef:
                            name: myapp-secrets
                            key: GOOGLE_CLIENT_ID
                      - name: GOOGLE_CLIENT_SECRET
                        valueFrom:
                          secretKeyRef:
                            name: myapp-secrets
                            key: GOOGLE_CLIENT_SECRET
                      - name: NEXTAUTH_SECRET
                        valueFrom:
                          secretKeyRef:
                            name: myapp-secrets
                            key: NEXTAUTH_SECRET
                      - name: NEXTAUTH_URL
                        valueFrom:
                          secretKeyRef:
                            name: myapp-secrets
                            key: NEXTAUTH_URL
                      - name: NEXT_PUBLIC_MAP_API_KEY
                        valueFrom:
                          secretKeyRef:
                            name: myapp-secrets
                            key: NEXT_PUBLIC_MAP_API_KEY
            imagePullSecrets:
                - name: github-registry
