apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-service
spec:
  replicas: 1
  revisionHistoryLimit: 1  # Keep only one old Replica Set as backup
  selector:
    matchLabels:
      app: website-service
  template:
    metadata:
      labels:
        app: website-service
    spec:
      containers:
        - name: website-service
          image: ghcr.io/2024-sdm-group5/website-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: github-registry
