import type { ReactNode } from 'react';

import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import { Inter } from 'next/font/google';

import Provider from '@/app/context/client-provider';

import { options } from './api/auth/[...nextauth]/options';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'NextAuth Demo',
};

type RootLayoutProps = {
	children: ReactNode;
};

async function RootLayout({ children }: RootLayoutProps) {
	const session = await getServerSession(options);
	return (
		<html lang="en">
			<body className={`${inter.className} min-h-screen bg-white`}>
				<Provider session={session}>{children}</Provider>
			</body>
		</html>
	);
}
export default RootLayout;
