name: CD Pipeline

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ghcr.io/2024-sdm-group5/website-service:latest
                  build-args: |
                    GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
                    GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
                    NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
                    NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
                    NEXT_PUBLIC_MAP_API_KEY=${{ secrets.NEXT_PUBLIC_MAP_API_KEY }}

            - name: Set up Kubectl
              uses: azure/setup-kubectl@v3

            - name: Configure Kubeconfig
              run: |
                  mkdir -p $HOME/.kube
                  echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config
                  chmod 600 $HOME/.kube/config

              # 使用 kubectl 與您的 Kubernetes 集群交互
            - name: Get Pods
              run: |
                  kubectl get pods

            - name: Deploy to Kubernetes
              run: |
                  kubectl apply -f k8s/deployment.yaml 
                  kubectl apply -f k8s/service.yaml 
                  # 如果有 Ingress
                  # kubectl apply -f k8s/ingress.yaml

            - name: Restart Deployment
              run: |
                  kubectl rollout restart -n default deployment website-service
